CREATE PROCEDURE [dbo].[USP_BPAG_PENDENTES] AS

------------------------------------------------------------------------------
-- CONDIÇÃO PARA ENTRAR NO METODO DE CRIACAO DE PRE-AUTORIZACAO
------------------------------------------------------------------------------
-- PREVENDA SEM RETORNO DO METODO DE PAYORDER(PRE-AUTORIZACAO)
-- PREVENDA NÃO PODE TER SIDO CANCELADA
-- PREVENDA DE CARTAO
-- PREVENDA NÃO PODE TER TRANSACAO DE CANCELAMENTO DE PRE-AUTORIZACAO PENDENTE
------------------------------------------------------------------------------
-------------------------------
--prevendas canceladas
-------------------------------
--if object_id('TempDb..#PREVENDAS_CANCELADAS')is not null
--   drop table #PREVENDAS_CANCELADAS 

--CREATE TABLE #PREVENDAS_CANCELADAS ( PREVENDA NUMERIC(15),TELEVENDA_ESTADO_LOG NUMERIC(30) )
--CREATE INDEX [IX_#PREVENDAS_CANCELADAS] ON [#PREVENDAS_CANCELADAS] (PREVENDA)

--INSERT INTO #PREVENDAS_CANCELADAS 
--     ( PREVENDA,
--       TELEVENDA_ESTADO_LOG 
--     )
--SELECT X.PREVENDA,
--       MAX(X.TELEVENDA_ESTADO_LOG) AS TELEVENDA_ESTADO_LOG  

--  FROM TELEVENDAS_ESTADO_COMANDAS_LOG X WITH(NOLOCK)                    
--  JOIN PDV_PREVENDAS                  Y WITH(NOLOCK) ON Y.PREVENDA = X.PREVENDA                   
-- WHERE Y.DATA >= GETDATE()--15 
--   AND Y.CARTAO > 0   
--   AND Y.PLATAFORMA_ECOMMERCE= 2
--   AND X.ESTADO = 99        
--   and 1 = 2
-- GROUP BY X.PREVENDA

--if object_id('TempDb..#BPAG_CANCELADA')is not null
--   drop table #BPAG_CANCELADA 

--SELECT X.PREVENDA, 
--       MAX(X.ID) AS ID
       
--  INTO #BPAG_CANCELADA
  
--  FROM PREVENDAS_BPAG_CANCEL      X WITH(NOLOCK) 
--  JOIN PDV_PREVENDAS              Y WITH(NOLOCK) ON Y.PREVENDA = X.PREVENDA 
--  LEFT JOIN #PREVENDAS_CANCELADAS A ON A.PREVENDA = Y.PREVENDA
-- WHERE Y.DATA >= GETDATE()--15
--   AND Y.PLATAFORMA_ECOMMERCE = 2
--   AND A.PREVENDA IS NULL
--   and 1 = 2

--  GROUP BY X.PREVENDA

SELECT TOP 1 
       B.ID, 
       A.PREVENDA, 
       B.XML_ENVIO
  FROM PDV_PREVENDAS                  A WITH(NOLOCK)
  JOIN PREVENDAS_BPAG_PAYORDER        B WITH(NOLOCK) ON B.PREVENDA = A.PREVENDA AND 1 = 2
  --LEFT JOIN #PREVENDAS_CANCELADAS     C              ON C.PREVENDA = A.PREVENDA
  --LEFT JOIN #BPAG_CANCELADA           D              ON D.PREVENDA = A.PREVENDA
  --LEFT JOIN PREVENDAS_BPAG_CANCEL     E WITH(NOLOCK) ON E.ID       = D.ID
  
 --WHERE A.DATA >= GETDATE()--15    
   --AND A.CARTAO > 0 
   --AND A.PLATAFORMA_ECOMMERCE = 2
   --AND B.XML_RETORNO IS NULL
   --AND C.TELEVENDA_ESTADO_LOG IS NULL
   --AND (E.ID IS NULL OR E.STATUS_WS = 0)
   --AND A.B2W_PEDIDO_INTERNET IS NULL
   --and 1 = 2

   
 --ORDER BY B.DATA_HORA --desc1
GO