CREATE PROCEDURE [dbo].[USP_BPAG_PENDENTES_PROBE]
AS

SELECT B.ID, A.PREVENDA, B.XML_ENVIO
  FROM PDV_PREVENDAS               A WITH(NOLOCK)
 INNER JOIN PREVENDAS_BPAG_PROBE   B WITH(NOLOCK) ON B.PREVENDA = A.PREVENDA
 WHERE B.XML_RETORNO IS NULL
   and A.CARTAO > 0 
   and 1 = 2
GO