CREATE PROCEDURE [dbo].[USP_BPAG_PENDENTES_CANCEL]
AS


--SELECT TOP 50 B.ID, A.PREVENDA, B.XML_ENVIO
--  FROM PDV_PREVENDAS                       A WITH(NOLOCK)
-- INNER JOIN PREVENDAS_BPAG_CANCEL          B WITH(NOLOCK) ON B.PREVENDA    = A.PREVENDA
-- WHERE B.XML_RETORNO IS NULL
--   and A.CARTAO > 0

SELECT TOP 1 B.ID, B.PREVENDA, B.XML_ENVIO
  FROM PREVENDAS_BPAG_CANCEL B WITH(NOLOCK) 
 WHERE B.XML_RETORNO IS NULL
GO