CREATE PROCEDURE [dbo].[USP_BPAG_CAPTURE_RETORNO](
                @PREVENDA_BPAG NUMERIC, 
                @PREVENDA      NUMERIC, 
				@XML           VARCHAR(MAX), 
				@XML_ORIGEM    VARCHAR(MAX), 
				@RETORNO       INT OUTPUT)
AS

IF CHARINDEX('partialCapture', @XML_ORIGEM) > 0
   EXEC USP_BPAG_CAPTURE_PARTIAL_RETORNO @PREVENDA_BPAG, @PREVENDA, @XML, @XML_ORIGEM, @RETORNO OUTPUT
ELSE
   EXEC USP_BPAG_CAPTURE_TOTAL_RETORNO   @PREVENDA_BPAG, @PREVENDA, @XML, @XML_ORIGEM, @RETORNO OUTPUT
GO