CREATE PROCEDURE [dbo].[USP_BPAG_CANCEL_RETORNO](@ID NUMERIC, @PREVENDA NUMERIC, @XML VARCHAR(MAX))
AS

DECLARE @AUX    XML
DECLARE @ESTADO NUMERIC(15)
DECLARE @STATUS_ESTORNO_PREAUTORIZACAO NUMERIC(15)
DECLARE @STATUS_CANCEL_PREAUTORIZACAO  NUMERIC(15)
DECLARE @PROCESSO VARCHAR(60)


SET @XML = REPLACE(@XML, '<?xml version="1.0" encoding="UTF-8"?>', '')

SET @AUX = CONVERT(XML, @XML)


UPDATE PREVENDAS_BPAG_CANCEL
   SET XML_RETORNO   = @AUX,
       status_ws     = @AUX.value('(cancelReturn/status)[1]', 'int'),
       prevenda_bpag = @AUX.value('(cancelReturn/bpag_data/id)[1]', 'numeric') ,
       status_bpag   = @AUX.value('(cancelReturn/fi_data/fi/status)[1]', 'numeric')
 WHERE ID = @ID 


SELECT @ESTADO = STATUS_CANCELAMENTO, 
       @STATUS_ESTORNO_PREAUTORIZACAO = STATUS_ESTORNO_PREAUTORIZACAO,
       @STATUS_CANCEL_PREAUTORIZACAO  = STATUS_CANCELAMENTO
 FROM PARAMETROS_BPAG A WITH(NOLOCK)



IF (SELECT ISNULL(ESTORNO,'N') 
      FROM PREVENDAS_BPAG_CANCEL WITH(NOLOCK) 
     WHERE ID =  @ID
   ) = 'S'

BEGIN
     SET @ESTADO   = @STATUS_ESTORNO_PREAUTORIZACAO
     SET @PROCESSO = 'ESTORNO'
END
ELSE
BEGIN
     SET @ESTADO = @STATUS_CANCEL_PREAUTORIZACAO
     SET @PROCESSO = 'CANCELAMENTO'
END
   

INSERT INTO TELEVENDAS_ESTADO_COMANDAS_LOG (
       REG_MASTER_ORIGEM,
       ESTADO,
       DATA_HORA,
       PREVENDA,
       PROCESSO,
       RESPONSAVEL,
       OBSERVACAO )
SELECT @ID,
       @ESTADO,
       GETDATE(),
       @PREVENDA,
       @PROCESSO,
       'BPAG',
       'USP_BPAG_CANCEL_RETORNO'
       
GO